version: '3'

services:

  mysql:
    image: mysql:8
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password    
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: espocrm
      MYSQL_USER: espocrm
      MYSQL_PASSWORD: espocrm
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306

  espocrm:
    image: webdevops/php-apache:8.0
    #image: espodev
    #build:
    #  context: ./docker
    #  dockerfile: Dockerfile.dev
    container_name: espocrm
    environment:
      ESPOCRM_DATABASE_HOST: localhost
      ESPOCRM_DATABASE_USER: espocrm
      ESPOCRM_DATABASE_PASSWORD: database_password
      ESPOCRM_ADMIN_USERNAME: admin
      ESPOCRM_ADMIN_PASSWORD: password
      ESPOCRM_SITE_URL: "http://localhost:8080"
    volumes:
      - ./build/EspoCRM-7.1.9:/app
      - ./home/superewald/Downloads/wkhtmltopdf/usr/local/bin/wkhtmltopdf:/usr/bin/wkhtmltopdf
    restart: always
    ports:
      - 8080:80

volumes:
  mysql: