version: '3'

services:

  mysql:
    image: mysql:8
    container_name: espo-db
    command: --default-authentication-plugin=mysql_native_password    
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: espocrm
      MYSQL_USER: espocrm
      MYSQL_PASSWORD: espocrm
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306

  espocrm:
    image: espodev
    build:
      context: ./docker
      dockerfile: Dockerfile.dev
    container_name: espo-dev
    environment:
      ESPOCRM_DATABASE_HOST: mysql
      ESPOCRM_DATABASE_USER: espocrm
      ESPOCRM_DATABASE_PASSWORD: espocrm
      ESPOCRM_ADMIN_USERNAME: admin
      ESPOCRM_ADMIN_PASSWORD: admin
      ESPOCRM_SITE_URL: "http://localhost:8080"
    volumes:
      - ./:/app
    restart: always
    ports:
      - 8080:80

volumes:
  mysql: